In [56]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score

In [3]:
train = pd.read_csv("fashion-mnist_train.csv")
train.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
train.describe()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,...,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000
mean,4.500000,0.000004,0.000024,0.000139,0.000400,0.000972,0.001614,0.003160,0.008621,0.022282,...,0.135786,0.091375,0.065052,0.070076,0.089470,0.070241,0.033414,0.010797,0.003355,0.000275
std,2.872305,0.000371,0.001063,0.004793,0.009619,0.016890,0.022887,0.032216,0.055268,0.093410,...,0.225668,0.191586,0.164626,0.172416,0.203257,0.177056,0.116137,0.068226,0.036694,0.008337
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.227451,0.035294,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,0.062745,0.141176,0.886275,0.643137,0.890196,0.901961,0.878431,1.000000,0.996078,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.666667

In [8]:
for col in train.columns[1:] :
     train[col] =train[col]/255

In [11]:
layer_0 =tf.keras.layers.Dense(units=len(train.columns[1:]),input_shape=[784])
layer_1 =tf.keras.layers.Dense(units=128 ,activation=tf.nn.relu )
layer_2 =tf.keras.layers.Dense(units=10 ,activation=tf.nn.softmax )

In [12]:
model =tf.keras.Sequential([layer_0,layer_1,layer_2] )

In [13]:
model.compile(loss="sparse_categorical_crossentropy" ,optimizer="adam" ,metrics=["accuracy"] )

In [16]:
model.fit(train[train.columns[1:]] ,train.label ,epochs=20)

Epoch 1/5
1875/1875 [==============================] - 16s 8ms/step - loss: 0.5148 - accuracy: 0.8141
Epoch 2/5
1875/1875 [==============================] - 14s 8ms/step - loss: 0.4053 - accuracy: 0.8523
Epoch 3/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.3763 - accuracy: 0.8632
Epoch 4/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.3615 - accuracy: 0.8686
Epoch 5/5
1875/1875 [==============================] - 14s 8ms/step - loss: 0.3448 - accuracy: 0.8738

In [30]:
test =pd.read_csv("fashion-mnist_test.csv")
predicted =model.predict(test[train.columns[1:]])

In [45]:
ans=[]
for i in range(len(predicted)) :     
     ans.append(np.argmax(predicted[i]))
     
test["predicted_label"] = ans

In [57]:
accuracy_score(test["label"] ,test["predicted_label"])

0.8577